"""Build curated question bank from IC3 GS6 Spark LV1 PDF (green check = correct)."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "questions.json"


def q(id_, topic, test_id, prompt, qtype, options, page=None, idx=None):
    return {
        "id": id_,
        "topic": topic,
        "testId": test_id,
        "prompt": prompt,
        "type": qtype,
        "options": [{"id": o[0], "text": o[1], "isCorrect": o[2]} for o in options],
        "page": page,
        "indexInTest": idx,
    }


questions = [
    # --- Chủ đề 1 Test 1 ---
    q(
        "t1-1-q3",
        "topic-1",
        "test-1",
        "Hai thiết bị nào sau đây là thiết bị ngoại vi? (Chọn 2)",
        "multiple",
        [
            ("A", "Bàn phím (Keyboard)", True),
            ("B", "Dây nguồn / adapter", False),
            ("C", "Chuột (Mouse)", True),
            ("D", "Thùng máy (System unit)", False),
        ],
        3,
        3,
    ),
    q(
        "t1-1-q4",
        "topic-1",
        "test-1",
        "Bạn cần kết nối máy tính bảng với Internet. Bạn nên sử dụng phương tiện gì?",
        "single",
        [
            ("A", "Monitor Cable", False),
            ("B", "Printer Cable", False),
            ("C", "Wifi", True),
            ("D", "Bluetooth", False),
        ],
        6,
        4,
    ),
    # --- Chủ đề 2 Test 1 ---
    q(
        "t2-1-q1",
        "topic-2",
        "test-1",
        "Quyền riêng tư kỹ thuật số là gì?",
        "single",
        [
            ("A", "Che Camera trên máy tính xách tay khi không sử dụng.", False),
            ("B", "Bảo vệ thông tin được lưu trữ hoặc chia sẻ trực tuyến.", True),
            ("C", "Trở thành bạn bè trực tuyến chỉ với những người bạn biết trong thế giới thực.", False),
            ("D", "Sử dụng mật khẩu phức tạp.", False),
        ],
        17,
        1,
    ),
    q(
        "t2-1-q2",
        "topic-2",
        "test-1",
        "Bạn thấy những bình luận ác ý trong một cuộc trò chuyện trong nhóm trực tuyến. Một công dân tốt của thời đại kỷ nguyên số, bạn nên nói gì?",
        "single",
        [
            ("A", "Chúng ta chỉ nên đăng những bình luận ác ý trong một cuộc trò chuyện riêng tư.", False),
            ("B", "Bạn có thể đăng những bình luận ác ý nếu người khác không nhìn thấy chúng.", False),
            ("C", "Bình luận ác ý là không gây hại nếu chúng bị xóa sau khi nhóm đọc chúng.", False),
            ("D", "Những bình luận này sẽ trực tuyến mãi mãi.", True),
        ],
        17,
        2,
    ),
    q(
        "t2-1-q3",
        "topic-2",
        "test-1",
        "Trolling là gì?",
        "single",
        [
            ("A", "Cố gắng làm cho ai đó tức giận bằng cách đăng những điều có ý nghĩa về họ.", True),
            ("B", "Cố tình bỏ ai đó ra ngoài.", False),
            ("C", "Đăng nhập vào trang cá nhân của người khác và mạo danh người đó.", False),
            ("D", "Chia sẻ thông tin cá nhân về ai đó mà không có sự cho phép của họ.", False),
        ],
        17,
        3,
    ),
    # --- Chủ đề 3 Test 1 ---
    q(
        "t3-1-q1",
        "topic-3",
        "test-1",
        "Bằng cách sử dụng tính năng Bookmarks/Favorites của trình duyệt Web, bạn có thể lưu gì?",
        "single",
        [
            ("A", "Hình ảnh trang Web", False),
            ("B", "Cookies trang Web", False),
            ("C", "Cài đặt trang Web", False),
            ("D", "Liên kết trang Web (Webpage Links)", True),
        ],
        23,
        1,
    ),
    q(
        "t3-1-q3-fact1",
        "topic-3",
        "test-1",
        "Nhà hàng có một khu trò chơi điện tử thực sự thú vị. Đây là Thực tế hay Ý kiến?",
        "single",
        [("A", "Thực tế", False), ("B", "Ý kiến", True)],
        23,
        3,
    ),
    q(
        "t3-1-q3-fact2",
        "topic-3",
        "test-1",
        "Nhà hàng có các món tráng miệng ngon nhất. Đây là Thực tế hay Ý kiến?",
        "single",
        [("A", "Thực tế", False), ("B", "Ý kiến", True)],
        23,
        3,
    ),
    q(
        "t3-1-q3-fact3",
        "topic-3",
        "test-1",
        "Nhà hàng chỉ cách trường học một dãy nhà. Đây là Thực tế hay Ý kiến?",
        "single",
        [("A", "Thực tế", True), ("B", "Ý kiến", False)],
        23,
        3,
    ),
    q(
        "t3-1-q3-fact4",
        "topic-3",
        "test-1",
        "Nhà hàng có mười loại Pizza khác nhau. Đây là Thực tế hay Ý kiến?",
        "single",
        [("A", "Thực tế", True), ("B", "Ý kiến", False)],
        23,
        3,
    ),
    q(
        "t3-1-match-browser",
        "topic-3",
        "test-1",
        "Trình duyệt Web (Web Browser) — định nghĩa đúng?",
        "single",
        [
            ("A", "Phần mềm bạn sử dụng để tìm mọi thứ trên Internet.", False),
            ("B", "Phần mềm bạn sử dụng để xem mọi thứ trên Internet.", True),
            ("C", "Một tài liệu với văn bản và hình ảnh trên Internet.", False),
        ],
        23,
        2,
    ),
    q(
        "t3-1-match-search",
        "topic-3",
        "test-1",
        "Công cụ tìm kiếm (Search Engine) — định nghĩa đúng?",
        "single",
        [
            ("A", "Phần mềm bạn sử dụng để tìm mọi thứ trên Internet.", True),
            ("B", "Phần mềm bạn sử dụng để xem mọi thứ trên Internet.", False),
            ("C", "Một tài liệu với văn bản và hình ảnh trên Internet.", False),
        ],
        23,
        2,
    ),
    # --- Chủ đề 4 Test 1 ---
    q(
        "t4-1-q1",
        "topic-4",
        "test-1",
        "Bạn nên sử dụng định dạng nào để hiển thị ảnh, bản đồ và Video từ kỳ nghỉ hè cho các bạn trong lớp xem?",
        "single",
        [
            ("A", "Một áp phích (Poster)", False),
            ("B", "Một tài liệu (Document)", False),
            ("C", "Một bài trình chiếu (Slide Presentation)", True),
            ("D", "Một trang tính (Spreadsheet)", False),
        ],
        34,
        1,
    ),
    q(
        "t4-1-q2-bold",
        "topic-4",
        "test-1",
        "In đậm văn bản — có phải định dạng văn bản không?",
        "single",
        [("A", "Có", True), ("B", "Không", False)],
        34,
        2,
    ),
    q(
        "t4-1-q2-delete",
        "topic-4",
        "test-1",
        "Xóa một phần của đoạn văn bản — có phải định dạng văn bản không?",
        "single",
        [("A", "Có", False), ("B", "Không", True)],
        34,
        2,
    ),
    q(
        "t4-1-q2-color",
        "topic-4",
        "test-1",
        "Thay đổi kích cỡ và màu sắc của văn bản — có phải định dạng văn bản không?",
        "single",
        [("A", "Có", True), ("B", "Không", False)],
        34,
        2,
    ),
    q(
        "t4-1-q3",
        "topic-4",
        "test-1",
        "Tổ hợp phím nào được sử dụng để chọn tất cả văn bản trong cùng một tài liệu?",
        "single",
        [
            ("A", "Alt + A", False),
            ("B", "Tab + A", False),
            ("C", "Shift + A", False),
            ("D", "Ctrl + A", True),
        ],
        34,
        3,
    ),
    # --- Chủ đề 5 Test 1 ---
    q(
        "t5-1-q2",
        "topic-5",
        "test-1",
        "Bạn cần gửi hai bức ảnh và hai đoạn văn về thằn lằn cho bạn làm áp phích nhóm. Bạn nên gửi bằng cách nào?",
        "single",
        [
            ("A", "Gửi bằng Email", True),
            ("B", "Gửi bằng tin nhắn văn bản", False),
            ("C", "Đăng trên mạng xã hội", False),
            ("D", "Trò chuyện Video", False),
        ],
        42,
        2,
    ),
    q(
        "t5-1-match-email",
        "topic-5",
        "test-1",
        "Một tin nhắn điện tử qua Internet có thể chứa văn bản, tập tin, hình ảnh — khái niệm nào?",
        "single",
        [
            ("A", "Thư điện tử (Email)", True),
            ("B", "Tin nhắn trong ứng dụng", False),
            ("C", "Trò chuyện Video", False),
        ],
        42,
        1,
    ),
    # --- Chủ đề 6 Test 1 ---
    q(
        "t6-1-q2",
        "topic-6",
        "test-1",
        "Phần thông tin nào là an toàn để chia sẻ trực tuyến?",
        "single",
        [
            ("A", "Màu sắc yêu thích của bạn.", True),
            ("B", "Địa điểm yêu thích của bạn.", False),
            ("C", "Tên trường của bạn.", False),
            ("D", "Công viên ưa thích của bạn.", False),
        ],
        53,
        2,
    ),
    q(
        "t6-1-q3",
        "topic-6",
        "test-1",
        "Khi nào thì có thể nói chuyện với người lạ trực tuyến?",
        "single",
        [
            ("A", "Không bao giờ", True),
            ("B", "Bất cứ lúc nào", False),
            ("C", "Ban ngày", False),
            ("D", "Cuối tuần", False),
        ],
        53,
        3,
    ),
    q(
        "t6-1-laptop-heat",
        "topic-6",
        "test-1",
        "Máy tính xách tay có thể bị hỏng nếu tiếp xúc với nhiệt độ khắc nghiệt.",
        "single",
        [("A", "Đúng", True), ("B", "Sai", False)],
        53,
        1,
    ),
    # --- Chủ đề 6 Test 2 ---
    q(
        "t6-2-q1",
        "topic-6",
        "test-2",
        "Cân bằng phương tiện (Media Balance) là gì?",
        "single",
        [
            ("A", "Sử dụng phương tiện để cảm thấy khỏe mạnh và cân bằng với các hoạt động sống khác.", True),
            ("B", "Dành tất cả thời gian rảnh trên điện thoại thông minh.", False),
            ("C", "Bản trình chiếu kết hợp hình ảnh, văn bản và âm thanh.", False),
        ],
        60,
        1,
    ),
    q(
        "t6-2-q2",
        "topic-6",
        "test-2",
        "Cách nào sau đây là an toàn nhất để sạc thiết bị di động?",
        "single",
        [
            ("A", "Đặt ở nơi an toàn gần ổ cắm và cắm cáp sạc đi kèm với thiết bị.", True),
            ("B", "Đặt thiết bị trên sàn và cắm cáp sạc của thiết bị khác.", False),
            ("C", "Sạc ngoài trời dưới ánh nắng trực tiếp.", False),
        ],
        60,
        2,
    ),
    q(
        "t6-2-q3",
        "topic-6",
        "test-2",
        "Bạn gửi ảnh gia đình cho bạn, bạn đăng lên mạng xã hội. Làm sao xóa ảnh vĩnh viễn khỏi Internet?",
        "single",
        [
            ("A", "Bạn không thể xóa ảnh mãi mãi, vì Internet là công khai và vĩnh viễn.", True),
            ("B", "Bảo bạn gỡ ảnh nếu không còn là bạn.", False),
            ("C", "Gửi yêu cầu hỗ trợ đến dịch vụ khách hàng.", False),
            ("D", "Đột nhập máy tính bạn và xóa ảnh.", False),
        ],
        60,
        3,
    ),
    # --- Chủ đề mở rộng ---
    q(
        "ext-1-q1",
        "topic-extended",
        "test-1",
        "Bài tập đại dương: cần ít nhất 3 sự kiện, không có ý kiến. Phát biểu nào là Ý kiến?",
        "single",
        [
            ("A", "Cá sống trong đại dương.", False),
            ("B", "Đại dương tối tăm và đáng sợ.", True),
            ("C", "Đại dương luôn chuyển động.", False),
            ("D", "Nhiều loại động vật sống trong đại dương.", False),
        ],
        66,
        1,
    ),
    q(
        "ext-1-q2",
        "topic-extended",
        "test-1",
        "Cộng tác (Collaboration) là gì?",
        "single",
        [
            ("A", "Khi mọi người làm việc với nhau để hoàn thành một nhiệm vụ.", True),
            ("B", "Làm việc trên máy tính hàng tuần.", False),
            ("C", "Cạnh tranh cho điểm tốt nhất trong lớp.", False),
        ],
        66,
        2,
    ),
    q(
        "ext-1-q3-alone",
        "topic-extended",
        "test-1",
        "Học sinh học được rằng cách tốt nhất để làm việc là làm việc một mình — Đúng hay Sai?",
        "single",
        [("A", "Đúng", False), ("B", "Sai", True)],
        66,
        3,
    ),
    q(
        "ext-1-q3-ideas",
        "topic-extended",
        "test-1",
        "Học sinh học hỏi từ ý tưởng của người khác — Đúng hay Sai?",
        "single",
        [("A", "Đúng", True), ("B", "Sai", False)],
        66,
        3,
    ),
]

payload = {
    "version": 1,
    "source": "On Thi IC3 GS6 SPARK LV1-Pass.pdf (curated from green checkmarks)",
    "total": len(questions),
    "questions": questions,
}

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Wrote {len(questions)} questions to {OUT}")
